#### Data Load

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
import math

In [2]:
Data_order_item= pd.read_csv('olist_order_items_dataset.csv')
Data_product= pd.read_csv('olist_products_dataset.csv')
Data_order_stat=pd.read_csv('olist_orders_dataset.csv')
Data_order_item.head()


order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1   
1  00018f77f2f0320c557190d7a144bdd3              1   
2  000229ec398224ef6ca0657da4fc703e              1   
3  00024acbcdf0a6daa1e931b038114c75              1   
4  00042b26cf59d7ce69dfabb4e55b4fd9              1   

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202   
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36   
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d   
3  7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4   
4  ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87   

   shipping_limit_date   price  freight_value  
0  2017-09-19 09:45:35   58.90          13.29  
1  2017-05-03 11:05:13  239.90          19.93  
2  2018-01-18 14:48:30  199.00          17.87  
3  2018-08-15 10:10:18   12.99          12.79  
4  2017-02-13 13:57:51  199.90          18.14

In [3]:
import string
import random
orderid=[]
number_of_strings = 112650
length_of_string = 32
for x in range(number_of_strings):
  orderid.append(''.join(random.choice(string.ascii_letters + string.digits) for _ in range(length_of_string)))
Data_order_item1=Data_order_item.sample(112650)
Data_order_item1.head()
Data_order_item1['order_id']=orderid
quantity1=[]
for i in range(112650):
    a=random.randint(1,3)
    quantity1.append(a)
Data_order_item1['order_item_id']=quantity1

In [4]:
orderid=[]
number_of_strings = 112650
length_of_string = 32
for x in range(number_of_strings):
  orderid.append(''.join(random.choice(string.ascii_letters + string.digits) for _ in range(length_of_string)))
Data_order_item_=Data_order_item.sample(112650)
Data_order_item_.head()
Data_order_item_['order_id']=orderid
quantity1=[]
for i in range(112650):
    a=random.randint(2,4)
    quantity1.append(a)
Data_order_item_['order_item_id']=quantity1

In [5]:
Data_order_item2=Data_order_item.append(Data_order_item1)
Data_order_item2=Data_order_item2.append(Data_order_item_)

In [6]:
len(Data_order_item2)

337950

### Overall Analysis

#### Product frequency

In [7]:
product_frequency= pd.DataFrame(Data_order_item.product_id.value_counts())
product_frequency.rename(columns={'product_id':'Quantity_sold'})
product_frequency.rename(columns={'':'product_id'})
print(product_frequency)
no_unique_products=len(product_frequency)
print(f'No_unique_products:{no_unique_products}')
unique_products=Data_order_item.product_id.unique()

                                  product_id
aca2eb7d00ea1a7b8ebd4e68314663af         527
99a4788cb24856965c36a24e339b6058         488
422879e10f46682990de24d770e7f83d         484
389d119b48cf3043d311335e499d9c6b         392
368c6c730842d78016ad823897a372db         388
...                                      ...
dbc42f8ad8afd0147a5a46be630781f8           1
5d86ed92606c80a89e547cdba3946812           1
0b8750fa58fefe42cf03a9e2e4b8fce6           1
a4758e74e2cdb74d0c4db83594ca14a3           1
350688d9dc1e75ff97be326363655e01           1

[32951 rows x 1 columns]
No_unique_products:32951


In [8]:
mean_unique_product=[]
mean_product_cost=[]
product_frequency=[]

for k in range (no_unique_products):
    temp1=pd.DataFrame(Data_order_item[Data_order_item.product_id == str(unique_products[k])])
    b=temp1.freight_value.mean()
    c=temp1.price.mean()
    d=temp1.product_id.count()
    mean_unique_product.append(b)
    mean_product_cost.append(c)
    product_frequency.append(d)
    k+=1

In [9]:
df_unique_product=pd.DataFrame({'product_id':unique_products,'mean_unique_product':mean_unique_product}, columns=['product_id','mean_unique_product'])
df_unique_product_price=pd.DataFrame({'product_id':unique_products,'mean_product_cost':mean_product_cost},columns=['product_id','mean_product_cost'])
df_product_frequency=pd.DataFrame({'product_id':unique_products,'Quantity_products_sold':product_frequency},columns=['product_id','Quantity_products_sold'])

In [10]:
df_unique_product

product_id  mean_unique_product
0      4244733e06e7ecb4970a6e2683c13e61            22.033333
1      e5f2d52b802189ee658865ca93d83a8f            19.930000
2      c777355d18b72b67abbeef9df44fd0fd            18.606667
3      7634da152a4610f1595efa32f14722fc            12.790000
4      ac6c3623068f30de03045865e4e10089            27.052500
...                                 ...                  ...
32946  4cc4d02efc8f249c13355147fb44e34d            51.200000
32947  b10ecf8e33aaaea419a9fa860ea80fb5            13.520000
32948  dd469c03ad67e201bc2179ef077dcd48            20.910000
32949  bbe7651fef80287a816ead73f065fc4b            44.020000
32950  350688d9dc1e75ff97be326363655e01            12.790000

[32951 rows x 2 columns]

In [11]:
print(df_unique_product_price)

                             product_id  mean_product_cost
0      4244733e06e7ecb4970a6e2683c13e61          59.233333
1      e5f2d52b802189ee658865ca93d83a8f         239.900000
2      c777355d18b72b67abbeef9df44fd0fd         199.000000
3      7634da152a4610f1595efa32f14722fc          12.990000
4      ac6c3623068f30de03045865e4e10089         202.400000
...                                 ...                ...
32946  4cc4d02efc8f249c13355147fb44e34d         129.900000
32947  b10ecf8e33aaaea419a9fa860ea80fb5          99.000000
32948  dd469c03ad67e201bc2179ef077dcd48         736.000000
32949  bbe7651fef80287a816ead73f065fc4b         229.900000
32950  350688d9dc1e75ff97be326363655e01          43.000000

[32951 rows x 2 columns]


In [12]:
product_high_freight_value=Data_order_item[Data_order_item.freight_value>=24.37].sort_values('freight_value',ascending=False)
product_high_freight_value.iloc[0:20,2:6]
t=pd.DataFrame(product_high_freight_value.product_id.unique())
t.iloc[0:30]
print(t)
df_unique_product=pd.DataFrame({'product_id':unique_products,'mean_product_freight_value':mean_unique_product},columns=['unique_seller_id','mean_freight_cost'])
#df_unique_product.head()
#df_unique_seller.head()

                                     0
0     ec31d2a17b299511e7c8627be9337b9b
1     a3cd9517ebf5a50dca25acce54f3b171
2     256a9c364b75753b97bee410c9491ad8
3     97c948ebc8c04b26b7bbb095d4228f2a
4     46e24ce614899e36617e37ea1e4aa6ff
...                                ...
9158  d1b571cd58267d8cac8b2afd6e288bbc
9159  5199c64bddaad759e3cc82d7fa449570
9160  fa9cf28beaafe4f4bec59550f6c76481
9161  fd6d9e3d204e6e693f4edd48ac33487e
9162  11147e87671eec98729e98e8e38c868b

[9163 rows x 1 columns]


#### Price/Cost analysis

In [13]:
Data_order_item['total_cost']=Data_order_item['price']+Data_order_item['freight_value']
Data_order_item['Freight_cost_%']=(Data_order_item['freight_value'])*100/(Data_order_item['total_cost'])
Data_order_item['Freight_cost_%'].describe()

count    112650.000000
mean         21.336434
std          12.949813
min           0.000000
25%          11.819196
50%          18.788733
75%          28.214357
max          96.328294
Name: Freight_cost_%, dtype: float64

In [14]:
item_sold_seller=pd.DataFrame(Data_order_item.seller_id.value_counts())
item_sold_seller.rename(columns={'seller_id':'items_sold'})
item_sold_seller



seller_id
6560211a19b47992c3666cc44a7e94c0       2033
4a3ca9315b744ce9f8e9374361493884       1987
1f50f920176fa81dab994f9023523100       1931
cc419e0650a3c5ba77189a1882b7556a       1775
da8622b14eb17ae2831f4ac5b9dab84a       1551
...                                     ...
400f221ab83037c0ea78f1267da9624d          1
1746c1ae87ac63d530c7c943d0ac42e2          1
16bdc8cefd0e32a6f0824d296c5ad14a          1
ace601496e211a664100321f038f50af          1
13d95f0f6f73943d4ceffad0fc2cd32c          1

[3095 rows x 1 columns]

In [15]:
unique_sellers=Data_order_item.seller_id.unique()
mean_unique_seller=[]
for j in range(len(unique_sellers)):
    temp=pd.DataFrame(Data_order_item[Data_order_item.seller_id == str(unique_sellers[j])])
    a=temp.freight_value.mean()
    mean_unique_seller.append(a)
    j+=1
df_unique_seller=pd.DataFrame({'unique_seller_id':unique_sellers,'mean_freight_cost':mean_unique_seller},columns=['unique_seller_id','mean_freight_cost'])
df_unique_seller=pd.DataFrame({'unique_seller_id':unique_sellers,'mean_freight_cost':mean_unique_seller})
df_unique_seller.sort_values('mean_freight_cost',ascending=False)
print(df_unique_seller.describe())
df_unique_seller[df_unique_seller.mean_freight_cost>=24.37].sort_values('mean_freight_cost',ascending=False)

       mean_freight_cost
count        3095.000000
mean           23.380116
std            18.957766
min             1.200000
25%            14.740000
50%            18.230000
75%            24.368333
max           308.336667


unique_seller_id  mean_freight_cost
930   6fa9202c10491e472dffd59a3e82b2a3         308.336667
2757  c88f62b4c386a59281014d677864d016         251.500000
3065  ee27a8f15b1dded4d213a468ba4eb391         227.660000
3093  80ceebb4ee9b31afb6c6a916a574a1e2         193.210000
168   56e361f411e38dcef17cdc2a3d99628b         185.776000
...                                ...                ...
2637  a3082f442524a1be452e3189e003b361          24.412500
2169  d558ebe531605a1285ab2b1bc3256dfb          24.410000
2021  23a0ffca143a15b9b5bbdb7d552f626a          24.407083
1622  f4ce8ca9fa7157e3b33f536ac9a4487d          24.382500
2380  9d213f303afae4983637247556438ede          24.370000

[774 rows x 2 columns]

#### Order time analysis

In [16]:
approved_orders= Data_order_stat[pd.notnull(Data_order_stat['order_approved_at'])]
shipped_orders= approved_orders[pd.notnull(approved_orders['order_delivered_customer_date'])]
never_delivered= shipped_orders[pd.isnull(shipped_orders['order_delivered_customer_date'])]
print('\n\nInstances where order was placed,approved,shipped but was never delivered to customer which result in loss/extra costing to company in terms of freight cost is :'+str(len(never_delivered)))
Data_order_stat.order_status.unique()
unavailable=len(Data_order_stat[Data_order_stat.order_status=='unavailable'])
print('\n\Total number of instances where inventory fell short i.e product was not available is:' +str (unavailable))

Data_order_stat.loc[:,'order_delivered_customer_date']=pd.to_datetime(Data_order_stat.loc[:,'order_delivered_customer_date'])
Data_order_stat.loc[:,'order_estimated_delivery_date']=pd.to_datetime(Data_order_stat.loc[:,'order_estimated_delivery_date'])
Data_order_stat['difference']=Data_order_stat.loc[:,'order_estimated_delivery_date']-Data_order_stat.loc[:,'order_delivered_customer_date']

delivery_time_difference=Data_order_stat[pd.notnull(Data_order_stat['difference'])]
delivery_time_difference.describe()

Early=0
on_time=0
Late=0

for i in range (len(delivery_time_difference['difference'])):
    if(delivery_time_difference.iloc[i,8]> pd.to_timedelta(0)):
        Early+=1
    if(delivery_time_difference.iloc[i,8]==pd.to_timedelta(0)):
        on_time+=1
    if(delivery_time_difference.iloc[i,8]< pd.to_timedelta(0)):
        Late+=1

Data_order_stat.loc[:,'order_purchase_timestamp']=pd.to_datetime(Data_order_stat.loc[:,'order_purchase_timestamp'])
Data_order_stat.loc[:,'order_delivered_customer_date']=pd.to_datetime(Data_order_stat.loc[:,'order_delivered_customer_date'])

Data_order_stat['actual_delivery_time']=Data_order_stat.loc[:,'order_delivered_customer_date']-Data_order_stat.loc[:,'order_purchase_timestamp']

actual_delivery_time=Data_order_stat[pd.notnull(Data_order_stat['actual_delivery_time'])]

actual_delivery_time.describe()
    



Instances where order was placed,approved,shipped but was never delivered to customer which result in loss/extra costing to company in terms of freight cost is :0

\Total number of instances where inventory fell short i.e product was not available is:609


difference        actual_delivery_time
count                       96476                       96476
mean   11 days 04:17:55.957616401  12 days 13:24:31.879068369
std    10 days 04:28:00.181984555   9 days 13:07:00.181125305
min           -189 days +00:35:53             0 days 12:48:07
25%               6 days 09:21:36      6 days 18:23:37.250000
50%       11 days 22:46:28.500000            10 days 05:13:34
75%       16 days 05:51:54.750000     15 days 17:17:16.250000
max             146 days 00:23:13           209 days 15:05:12

In [17]:
delivery_time_difference.iloc[0:3,8]

0    7 days 02:34:47
1    5 days 08:32:15
2   17 days 05:53:31
Name: difference, dtype: timedelta64[ns]

### Simulation Variables

In [18]:
storage_locations=1140
pod=1100
c=2
r=25
aisles=20
cross_Ailes=10
shelves=35
SKU=no_unique_products
total_shelve_volume=40*30*120
product_shelve=3
total_pod_weight=1000000
picking_Zone=1
shelves_layout=np.zeros((20))
pods_layout=np.array(np.zeros((pod,shelves,product_shelve)))
shelves_capacity=pod*shelves

In [19]:
pods_layout.shape

(1100, 35, 3)

In [20]:
pods_layout

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### Data preprocessing

#### Average daily inventory

In [21]:
df=pd.DataFrame({'product_id':unique_products,'Quantity_products_sold':product_frequency,'total_cost':mean_product_cost},columns=['product_id','Quantity_products_sold','total_cost'])
df['Quantity_products_sold']=df['Quantity_products_sold']
df

product_id  Quantity_products_sold  total_cost
0      4244733e06e7ecb4970a6e2683c13e61                       9   59.233333
1      e5f2d52b802189ee658865ca93d83a8f                       1  239.900000
2      c777355d18b72b67abbeef9df44fd0fd                       3  199.000000
3      7634da152a4610f1595efa32f14722fc                       2   12.990000
4      ac6c3623068f30de03045865e4e10089                      12  202.400000
...                                 ...                     ...         ...
32946  4cc4d02efc8f249c13355147fb44e34d                       1  129.900000
32947  b10ecf8e33aaaea419a9fa860ea80fb5                       1   99.000000
32948  dd469c03ad67e201bc2179ef077dcd48                       1  736.000000
32949  bbe7651fef80287a816ead73f065fc4b                       1  229.900000
32950  350688d9dc1e75ff97be326363655e01                       1   43.000000

[32951 rows x 3 columns]

In [22]:
df2= pd.merge(df,Data_product,on='product_id')
df2['volume_cm3']=df2['product_length_cm']*df2['product_height_cm']*df2['product_width_cm']
df2['average_daily_quantity']=df2['Quantity_products_sold']/30
df2

product_id  Quantity_products_sold  total_cost  \
0      4244733e06e7ecb4970a6e2683c13e61                       9   59.233333   
1      e5f2d52b802189ee658865ca93d83a8f                       1  239.900000   
2      c777355d18b72b67abbeef9df44fd0fd                       3  199.000000   
3      7634da152a4610f1595efa32f14722fc                       2   12.990000   
4      ac6c3623068f30de03045865e4e10089                      12  202.400000   
...                                 ...                     ...         ...   
32946  4cc4d02efc8f249c13355147fb44e34d                       1  129.900000   
32947  b10ecf8e33aaaea419a9fa860ea80fb5                       1   99.000000   
32948  dd469c03ad67e201bc2179ef077dcd48                       1  736.000000   
32949  bbe7651fef80287a816ead73f065fc4b                       1  229.900000   
32950  350688d9dc1e75ff97be326363655e01                       1   43.000000   

      product_category_name  product_name_lenght  product_description_lenght  \
0                cool_stuff                 58.0                       598.0   
1                  pet_shop                 56.0                       239.0   
2          moveis_decoracao                 59.0                       695.0   
3                perfumaria                 42.0                       480.0   
4        ferramentas_jardim                 59.0                       409.0   
...                     ...                  ...                         ...   
32946    ferramentas_jardim                 37.0                       653.0   
32947      moveis_decoracao                 30.0                       308.0   
32948    relogios_presentes                 33.0                       658.0   
32949         esporte_lazer                 32.0                       280.0   
32950       cama_mesa_banho                 47.0                       511.0   

       product_photos_qty  product_weight_g  product_length_cm  \
0                     4.0             650.0               28.0   
1                     2.0           30000.0               50.0   
2                     2.0            3050.0               33.0   
3                     1.0             200.0               16.0   
4                     1.0            3750.0               35.0   
...                   ...               ...                ...   
32946                 1.0            6700.0               35.0   
32947                 1.0            2300.0               37.0   
32948                 3.0             400.0               19.0   
32949                 2.0            2700.0               60.0   
32950                 1.0             600.0               30.0   

       product_height_cm  product_width_cm  volume_cm3  average_daily_quantity  
0                    9.0              14.0      3528.0                0.300000  
1                   30.0              40.0     60000.0                0.033333  
2                   13.0              33.0     14157.0                0.100000  
3                   10.0              15.0      2400.0                0.066667  
4                   40.0              30.0     42000.0                0.400000  
...                  ...               ...         ...                     ...  
32946               12.0              22.0      9240.0                0.033333  
32947               30.0              20.0     22200.0                0.033333  
32948                9.0              15.0      2565.0                0.033333  
32949               15.0              15.0     13500.0                0.033333  
32950                3.0              19.0      1710.0                0.033333  

[32951 rows x 13 columns]

In [23]:
# filter=df2['average_monthly_quantity']>3
# df_filter=df2[filter]
# df_filter

In [24]:
df2.average_daily_quantity.describe()

count    32951.000000
mean         0.113957
std          0.353990
min          0.033333
25%          0.033333
50%          0.033333
75%          0.100000
max         17.566667
Name: average_daily_quantity, dtype: float64

In [25]:
print(Data_product.product_length_cm.describe())
print(Data_product.product_height_cm.describe())
print(Data_product.product_width_cm.describe())


count    32949.000000
mean        30.815078
std         16.914458
min          7.000000
25%         18.000000
50%         25.000000
75%         38.000000
max        105.000000
Name: product_length_cm, dtype: float64
count    32949.000000
mean        16.937661
std         13.637554
min          2.000000
25%          8.000000
50%         13.000000
75%         21.000000
max        105.000000
Name: product_height_cm, dtype: float64
count    32949.000000
mean        23.196728
std         12.079047
min          6.000000
25%         15.000000
50%         20.000000
75%         30.000000
max        118.000000
Name: product_width_cm, dtype: float64


In [26]:
df2=df2.drop(['Quantity_products_sold','product_name_lenght','product_description_lenght','product_photos_qty','product_length_cm','product_height_cm','product_width_cm'],axis=1)
df2.dropna()
df2 = df2.drop_duplicates(subset= ['product_id'] ,keep = 'first')


#### Standard deviation

In [27]:
df_std=Data_order_item2.groupby('product_id').std()[['order_item_id']]
df_std.rename(columns={'order_item_id':'std'})
df_std

order_item_id
product_id                                     
00066f42aeeb9f3007548bb9d3f33c38       0.577350
00088930e925c41fd95ebfe695fd2655       1.000000
0009406fd7479715e4bef61dd91f2462       1.154701
000b8f95fcb9e0096488278317764d19       1.366260
000d9be29b5207b54e86aa1b1ac54872       0.577350
...                                         ...
fff6177642830a9a94a0f2cba5e476d1       1.211060
fff81cc3158d2725c0655ab9ba0f712c       1.000000
fff9553ac224cec9d15d49f5a263411f       1.527525
fffdb2d0ec8d6a61f0a0a0db3f25b441       1.125463
fffe9eeff12fcbd74a2f2b007dde0c58       1.154701

[32951 rows x 1 columns]

In [28]:
df_std.isnull().sum()

order_item_id    0
dtype: int64

In [29]:
df2=pd.merge(df2,df_std,on='product_id')
df2=df2.rename(columns={'order_item_id':'std'})

In [30]:
df2.isnull().sum()


product_id                  0
total_cost                  0
product_category_name     610
product_weight_g            2
volume_cm3                  2
average_daily_quantity      0
std                         0
dtype: int64

In [31]:
df2=df2[pd.notnull(df2['volume_cm3'])]
df2=df2[pd.notnull(df2['product_weight_g'])]
df2.isnull().sum()

product_id                  0
total_cost                  0
product_category_name     609
product_weight_g            0
volume_cm3                  0
average_daily_quantity      0
std                         0
dtype: int64

In [32]:
conditions2 =[(df2['std']<0.341),(df2['std']>=0.341)|(df2['std']<0.477), (df2['std']>=0.477)]
sigma= [1,2,3]
df2['std_sigma']=np.select(conditions2,sigma)
df2

product_id  total_cost product_category_name  \
0      4244733e06e7ecb4970a6e2683c13e61   59.233333            cool_stuff   
1      e5f2d52b802189ee658865ca93d83a8f  239.900000              pet_shop   
2      c777355d18b72b67abbeef9df44fd0fd  199.000000      moveis_decoracao   
3      7634da152a4610f1595efa32f14722fc   12.990000            perfumaria   
4      ac6c3623068f30de03045865e4e10089  202.400000    ferramentas_jardim   
...                                 ...         ...                   ...   
32946  4cc4d02efc8f249c13355147fb44e34d  129.900000    ferramentas_jardim   
32947  b10ecf8e33aaaea419a9fa860ea80fb5   99.000000      moveis_decoracao   
32948  dd469c03ad67e201bc2179ef077dcd48  736.000000    relogios_presentes   
32949  bbe7651fef80287a816ead73f065fc4b  229.900000         esporte_lazer   
32950  350688d9dc1e75ff97be326363655e01   43.000000       cama_mesa_banho   

       product_weight_g  volume_cm3  average_daily_quantity       std  \
0                 650.0      3528.0                0.300000  0.979854   
1               30000.0     60000.0                0.033333  1.154701   
2                3050.0     14157.0                0.100000  0.500000   
3                 200.0      2400.0                0.066667  0.983192   
4                3750.0     42000.0                0.400000  1.067559   
...                 ...         ...                     ...       ...   
32946            6700.0      9240.0                0.033333  1.000000   
32947            2300.0     22200.0                0.033333  1.154701   
32948             400.0      2565.0                0.033333  1.732051   
32949            2700.0     13500.0                0.033333  1.527525   
32950             600.0      1710.0                0.033333  1.527525   

       std_sigma  
0              2  
1              2  
2              2  
3              2  
4              2  
...          ...  
32946          2  
32947          2  
32948          2  
32949          2  
32950          2  

[32949 rows x 8 columns]

In [33]:
df2['std'].describe()

count    32949.000000
mean         1.095534
std          0.333455
min          0.000000
25%          0.971825
50%          1.092906
75%          1.224745
max         11.269428
Name: std, dtype: float64

#### Inventory Policy

In [34]:
def inventory (col):
    c1 = col[0]
    c2 = col[1]

    if c1 == 1:
        return c2 * 0.5
    elif c1 == 2:
        return c2 * 0.75
    else:
        return c2


In [35]:
df2['safety_stock'] = df2[['std_sigma','average_daily_quantity']].apply( inventory, axis =1)


In [36]:
df2['total_inventory']=df2['average_daily_quantity']+df2['safety_stock']
df2['total_inventory']=df2['total_inventory'].apply(np.ceil)

In [37]:
df2

product_id  total_cost product_category_name  \
0      4244733e06e7ecb4970a6e2683c13e61   59.233333            cool_stuff   
1      e5f2d52b802189ee658865ca93d83a8f  239.900000              pet_shop   
2      c777355d18b72b67abbeef9df44fd0fd  199.000000      moveis_decoracao   
3      7634da152a4610f1595efa32f14722fc   12.990000            perfumaria   
4      ac6c3623068f30de03045865e4e10089  202.400000    ferramentas_jardim   
...                                 ...         ...                   ...   
32946  4cc4d02efc8f249c13355147fb44e34d  129.900000    ferramentas_jardim   
32947  b10ecf8e33aaaea419a9fa860ea80fb5   99.000000      moveis_decoracao   
32948  dd469c03ad67e201bc2179ef077dcd48  736.000000    relogios_presentes   
32949  bbe7651fef80287a816ead73f065fc4b  229.900000         esporte_lazer   
32950  350688d9dc1e75ff97be326363655e01   43.000000       cama_mesa_banho   

       product_weight_g  volume_cm3  average_daily_quantity       std  \
0                 650.0      3528.0                0.300000  0.979854   
1               30000.0     60000.0                0.033333  1.154701   
2                3050.0     14157.0                0.100000  0.500000   
3                 200.0      2400.0                0.066667  0.983192   
4                3750.0     42000.0                0.400000  1.067559   
...                 ...         ...                     ...       ...   
32946            6700.0      9240.0                0.033333  1.000000   
32947            2300.0     22200.0                0.033333  1.154701   
32948             400.0      2565.0                0.033333  1.732051   
32949            2700.0     13500.0                0.033333  1.527525   
32950             600.0      1710.0                0.033333  1.527525   

       std_sigma  safety_stock  total_inventory  
0              2         0.225              1.0  
1              2         0.025              1.0  
2              2         0.075              1.0  
3              2         0.050              1.0  
4              2         0.300              1.0  
...          ...           ...              ...  
32946          2         0.025              1.0  
32947          2         0.025              1.0  
32948          2         0.025              1.0  
32949          2         0.025              1.0  
32950          2         0.025              1.0  

[32949 rows x 10 columns]

In [38]:
df2['total_inventory'].describe()

count    32949.000000
mean         1.054539
std          0.572979
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         31.000000
Name: total_inventory, dtype: float64

In [39]:
product=df2['product_id'].tolist()
product_inventory=df2['total_inventory'].tolist()
product_weight=df2['product_weight_g'].tolist()
product_volume=df2['volume_cm3'].tolist()
product_category=df2['product_category_name'].tolist()
dict_product_={}
for i,j,k,l,m in zip (product,product_category,product_inventory,product_weight,product_volume):
    dict_product_[i]=[j,k,l,m]
dict_product_

{'4244733e06e7ecb4970a6e2683c13e61': ['cool_stuff', 1.0, 650.0, 3528.0],
 'e5f2d52b802189ee658865ca93d83a8f': ['pet_shop', 1.0, 30000.0, 60000.0],
 'c777355d18b72b67abbeef9df44fd0fd': ['moveis_decoracao',
  1.0,
  3050.0,
  14157.0],
 '7634da152a4610f1595efa32f14722fc': ['perfumaria', 1.0, 200.0, 2400.0],
 'ac6c3623068f30de03045865e4e10089': ['ferramentas_jardim',
  1.0,
  3750.0,
  42000.0],
 'ef92defde845ab8450f9d70c526ef70f': ['utilidades_domesticas',
  1.0,
  450.0,
  2880.0],
 '8d4f2bb7e93e6710a28f34fa83ee7d28': ['telefonia', 1.0, 200.0, 2700.0],
 '557d850972a7d6f792fd18ae1400d9b6': ['ferramentas_jardim',
  1.0,
  13805.0,
  118125.0],
 '310ae3c140ff94b03219ad0adc3c778f': ['beleza_saude', 1.0, 2000.0, 5760.0],
 '4535b0e1091c278dfd193e5a1d63b39f': ['livros_tecnicos', 1.0, 850.0, 1827.0],
 'd63c1011f49d98b976c352955b1c4bea': ['beleza_saude', 4.0, 950.0, 17500.0],
 'f177554ea93259a5b282f24e33f65ab6': ['fashion_bolsas_e_acessorios',
  1.0,
  200.0,
  2816.0],
 '99a4788cb24856965c36a24

In [40]:
df2.total_inventory.sum()

34746.0

#### Label Encoding

In [41]:
# from sklearn.preprocessing import LabelEncoder
# lbl=LabelEncoder()
# cols=['product_id','product_category_name']

# for col in cols:
#     df2[col]=lbl.fit_transform(df2[col])
# df2.head()


### Classification Algorithms

#### Asocciation Rules

In [42]:
df_association=pd.merge(Data_order_item,Data_product,on='product_id')
df_association.dropna(axis=0,inplace=True)
df_association

order_id  order_item_id  \
0       00010242fe8c5a6d1ba2dd792cb16214              1   
1       130898c0987d1801452a8ed92a670612              1   
2       532ed5e14e24ae1f0d735b91524b98b9              1   
3       6f8c31653edb8c83e1a739408b5ff750              1   
4       7d19f4ef4d04461989632411b7e588b9              1   
...                                  ...            ...   
112645  ffebd80e3291e811c308365936897efd              1   
112646  ffee31fb4b5e35c9123608015637c495              1   
112647  fff7c4452f050315db1b3f24d9df5fcd              1   
112648  fffa82886406ccf10c7b4e35c4ff2788              1   
112649  fffe41c64501cc87c801fd61db3f6244              1   

                              product_id                         seller_id  \
0       4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202   
1       4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202   
2       4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202   
3       4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202   
4       4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202   
...                                  ...                               ...   
112645  4cc4d02efc8f249c13355147fb44e34d  d1c7fa84e48cfa21a0e595167c1c500e   
112646  b10ecf8e33aaaea419a9fa860ea80fb5  0241d4d5d36f10f80c644447315af0bd   
112647  dd469c03ad67e201bc2179ef077dcd48  7e93a43ef30c4f03f38b393420bc753a   
112648  bbe7651fef80287a816ead73f065fc4b  8f2ce03f928b567e3d56181ae20ae952   
112649  350688d9dc1e75ff97be326363655e01  f7ccf836d21b2fb1de37564105216cc1   

        shipping_limit_date  price  freight_value  total_cost  Freight_cost_%  \
0       2017-09-19 09:45:35   58.9          13.29       72.19       18.409752   
1       2017-07-05 02:44:11   55.9          17.96       73.86       24.316274   
2       2018-05-23 10:56:25   64.9          18.33       83.23       22.023309   
3       2017-08-07 18:55:08   58.9          16.17       75.07       21.539896   
4       2017-08-16 22:05:11   58.9          13.29       72.19       18.409752   
...                     ...    ...            ...         ...             ...   
112645  2018-07-18 20:23:55  129.9          51.20      181.10       28.271673   
112646  2018-08-21 10:10:11   99.0          13.52      112.52       12.015642   
112647  2017-06-07 17:05:23  736.0          20.91      756.91        2.762548   
112648  2017-12-22 17:31:42  229.9          44.02      273.92       16.070386   
112649  2018-06-12 17:10:13   43.0          12.79       55.79       22.925255   

       product_category_name  product_name_lenght  product_description_lenght  \
0                 cool_stuff                 58.0                       598.0   
1                 cool_stuff                 58.0                       598.0   
2                 cool_stuff                 58.0                       598.0   
3                 cool_stuff                 58.0                       598.0   
4                 cool_stuff                 58.0                       598.0   
...                      ...                  ...                         ...   
112645    ferramentas_jardim                 37.0                       653.0   
112646      moveis_decoracao                 30.0                       308.0   
112647    relogios_presentes                 33.0                       658.0   
112648         esporte_lazer                 32.0                       280.0   
112649       cama_mesa_banho                 47.0                       511.0   

        product_photos_qty  product_weight_g  product_length_cm  \
0                      4.0             650.0               28.0   
1                      4.0             650.0               28.0   
2                      4.0             650.0               28.0   
3                      4.0             650.0               28.0   
4                      4.0             650.0               28.0   
...                    ...            

In [43]:
category_products=df_association.groupby('product_category_name').count()[['product_id']]
category_products

product_id
product_category_name                
agro_industria_e_comercio         212
alimentos                         510
alimentos_bebidas                 278
artes                             209
artes_e_artesanato                 24
...                               ...
sinalizacao_e_seguranca           199
tablets_impressao_imagem           83
telefonia                        4545
telefonia_fixa                    264
utilidades_domesticas            6964

[73 rows x 1 columns]

In [44]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from mlxtend.preprocessing import TransactionEncoder

In [45]:
dataset_association=pd.DataFrame(df_association[{'order_id','product_category_name'}])
dataset_association=dataset_association.reindex(columns=['order_id','product_category_name'])
dataset_association

order_id product_category_name
0       00010242fe8c5a6d1ba2dd792cb16214            cool_stuff
1       130898c0987d1801452a8ed92a670612            cool_stuff
2       532ed5e14e24ae1f0d735b91524b98b9            cool_stuff
3       6f8c31653edb8c83e1a739408b5ff750            cool_stuff
4       7d19f4ef4d04461989632411b7e588b9            cool_stuff
...                                  ...                   ...
112645  ffebd80e3291e811c308365936897efd    ferramentas_jardim
112646  ffee31fb4b5e35c9123608015637c495      moveis_decoracao
112647  fff7c4452f050315db1b3f24d9df5fcd    relogios_presentes
112648  fffa82886406ccf10c7b4e35c4ff2788         esporte_lazer
112649  fffe41c64501cc87c801fd61db3f6244       cama_mesa_banho

[111046 rows x 2 columns]

In [46]:
unique_order=dataset_association.order_id.unique()
len(unique_order)

97276

In [47]:
# dictionary={}
# for data in unique_order:
#     tmp_1=dataset_association[dataset_association['order_id']==data]['product_category_name'].values#filtro para valor unico de orden 
#     dictionary[data]=tmp_1
    

In [48]:
categories=[]
for data in unique_order:
    tmp_1=dataset_association[dataset_association['order_id']==data]['product_category_name'].values #filtro para valor unico de orden 
    categories.append(tmp_1)

In [49]:
# product_dict=[]
# for data in unique_order:
#     tmp_1=dataset_association[dataset_association['order_id']==data]['product_id'].values #filtro para valor unico de orden 
#     product_dict.append(tmp_1)


In [50]:
unique_category=dataset_association.product_category_name.unique()
len(unique_category)

73

In [51]:
te = TransactionEncoder()
te_ary = te.fit_transform(np.array(categories,dtype='object'))
dataset_association2 = pd.DataFrame(te_ary,columns=te.columns_)
dataset_association2 

agro_industria_e_comercio  alimentos  alimentos_bebidas  artes  \
0                          False      False              False  False   
1                          False      False              False  False   
2                          False      False              False  False   
3                          False      False              False  False   
4                          False      False              False  False   
...                          ...        ...                ...    ...   
97271                      False      False              False  False   
97272                      False      False              False  False   
97273                      False      False              False  False   
97274                      False      False              False  False   
97275                      False      False              False  False   

       artes_e_artesanato  artigos_de_festas  artigos_de_natal  audio  \
0                   False              False             False  False   
1                   False              False             False  False   
2                   False              False             False  False   
3                   False              False             False  False   
4                   False              False             False  False   
...                   ...                ...               ...    ...   
97271               False              False             False  False   
97272               False              False             False  False   
97273               False              False             False  False   
97274               False              False             False  False   
97275               False              False             False  False   

       automotivo  bebes  ...  pet_shop  portateis_casa_forno_e_cafe  \
0           False  False  ...     False                        False   
1           False  False  ...     False                        False   
2           False  False  ...     False                        False   
3           False  False  ...     False                        False   
4           False  False  ...     False                        False   
...           ...    ...  ...       ...                          ...   
97271       False  False  ...     False                        False   
97272       False  False  ...     False                        False   
97273       False  False  ...     False                        False   
97274       False  False  ...     False                        False   
97275       False  False  ...     False                        False   

       portateis_cozinha_e_preparadores_de_alimentos  relogios_presentes  \
0                                              False               False   
1                                              False               False   
2                                              False               False   
3                                              False               False   
4                                              False               False   
...                                              ...                 ...   
97271                                          False               False   
97272                                          False               False   
97273                                          False                True   
97274                                          False               False   
97275                                          False               False   

       seguros_e_servicos  sinalizacao_e_seguranca  tablets_impressao_imagem  \
0                   False                    False                     False   
1                   False                    False                     False   
2                   False                    False                     False   
3                   False                    False                     False   
4                   False                    False                     Fals

In [52]:
len(te.columns_)

73

In [53]:
from mlxtend.frequent_patterns import apriori

frequent_itemsets=apriori(dataset_association2, min_support=0.0005,use_colnames=True) #run the association rule algorithm
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets

support                                          itemsets  length
0   0.001871                       (agro_industria_e_comercio)       1
1   0.004626                                       (alimentos)       1
2   0.002334                               (alimentos_bebidas)       1
3   0.002077                                           (artes)       1
4   0.001316                                (artigos_de_natal)       1
5   0.003598                                           (audio)       1
6   0.040061                                      (automotivo)       1
7   0.029648                                           (bebes)       1
8   0.003053                                         (bebidas)       1
9   0.090834                                    (beleza_saude)       1
10  0.039948                                      (brinquedos)       1
11  0.096807                                 (cama_mesa_banho)       1
12  0.004081                                   (casa_conforto)       1
13  0.005037                                 (casa_construcao)       1
14  0.000668                                       (cine_foto)       1
15  0.002601                                    (climatizacao)       1
16  0.010917                                  (consoles_games)       1
17  0.007689               (construcao_ferramentas_construcao)       1
18  0.000997              (construcao_ferramentas_ferramentas)       1
19  0.002508               (construcao_ferramentas_iluminacao)       1
20  0.001994                   (construcao_ferramentas_jardim)       1
21  0.001717                (construcao_ferramentas_seguranca)       1
22  0.037337                                      (cool_stuff)       1
23  0.000607                                    (dvds_blu_ray)       1
24  0.007854                                (eletrodomesticos)       1
25  0.002406                              (eletrodomesticos_2)       1
26  0.026214                                     (eletronicos)       1
27  0.006476                                 (eletroportateis)       1
28  0.079362                                   (esporte_lazer)       1
29  0.019162                     (fashion_bolsas_e_acessorios)       1
30  0.002467                                (fashion_calcados)       1
31  0.001151                         (fashion_roupa_masculina)       1
32  0.001244                  (fashion_underwear_e_moda_praia)       1
33  0.036165                              (ferramentas_jardim)       1
34  0.002416                   (industria_comercio_e_negocios)       1
35  0.068763                          (informatica_acessorios)       1
36  0.006456                           (instrumentos_musicais)       1
37  0.000545                               (livros_importados)       1
38  0.005263                          (livros_interesse_geral)       1
39  0.002673                                 (livros_tecnicos)       1
40  0.010630                                (malas_acessorios)       1
41  0.002878                                    (market_place)       1
42  0.002549  (moveis_cozinha_area_de_servico_jantar_e_jardim)       1
43  0.066296                                (moveis_decoracao)       1
44  0.013086                               (moveis_escritorio)       1
45  0.000977                                   (moveis_quarto)       1
46  0.004338                                     (moveis_sala)       1
47  0.023757                                       (papelaria)       1
48  0.001861                                             (pcs)       1
49  0.032505                                      (perfumaria)       1
50  0.017579                                        (pet_shop)       1
51  0.000771                     (portateis_casa_forno_e_cafe)       1
52  0.057815                              (relogios_presentes)       1
53  0.001439                         (sinalizacao_e_seguranca)       1
54  0.000812                        (tablets_impressao_imagem)       1
55  0.043166                 

In [54]:
from mlxtend.frequent_patterns import association_rules

rules=association_rules(frequent_itemsets, metric="lift", min_threshold=0.8)

In [55]:
rules["antecedent_len"] = rules["antecedents"].apply(lambda x: len(x))
rules["consequents_len"] = rules["consequents"].apply(lambda x: len(x))
df_rules=rules[ (rules['antecedent_len'] == 1) &(rules['consequents_len'] ==1) &
       (rules['conviction'] >1)
        ]
df_rules

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction, antecedent_len, consequents_len]
Index: []

In [56]:
antecedents=[]
for i in df_rules['antecedents'].values:
    a=list(i)[0]
    antecedents.append(a)
#antecedents

In [57]:
consequence=[]
for i in df_rules['consequents'].values:
    a=list(i)[:]
    consequence.append(a)
#consequence

In [58]:
rules1={}
for i,j in zip (antecedents,consequence):
    rules1[i]=j

In [59]:
rules1

{}

#### kmeans

In [60]:
# from sklearn import preprocessing

# #normalization
# min_max_scaler = preprocessing.MinMaxScaler()
# Dataset_normalize = min_max_scaler.fit_transform(df2)
# np.shape(Dataset_normalize)

In [61]:
# from sklearn.cluster import KMeans
# x=Dataset_normalize[:,[1]]
# km1 = KMeans(n_clusters=2) # run k means
# km1.fit(x)
# print(km1.labels_)
# len(km1.labels_)
# cluster=km1.labels_.T

In [62]:
# from sklearn import metrics
# score = metrics.silhouette_score(x, km1.labels_, metric='euclidean')
# print(score)

In [63]:
# from sklearn.metrics import silhouette_samples,silhouette_score
# import matplotlib.cm as cm
# import matplotlib.pyplot as plt
# import seaborn as sns
# def Best_Kmean(x,k,random_state=104):
    
#     #taking Dataset copy to Find Clusters
#     df_cluster = df.copy
    
#     # Creting K
#     silhouette_=[]
#     Inertia = []
#     range_n_clusters = list(range(2,k+1))
#     time = 0
    
    
#     for n_clusters in range_n_clusters:
#         fig,(ax1,ax2,ax3) = plt.subplots(1,3,figsize =(25,5))
#         ax1.set_xlim([-0.1, 1])
#         ax1.set_ylim([0, len(x) + (n_clusters + 1) * 10])
        
#         clusterer = KMeans(n_clusters=n_clusters, random_state=random_state,init = 'k-means++')
#         cluster_labels = clusterer.fit_predict(x)
#         silhouette_avg = silhouette_score(x, cluster_labels)
#         silhouette_.append(silhouette_avg)
#         Inertia.append(clusterer.inertia_)
#         unique, counts = np.unique(cluster_labels, return_counts=True)
#         #print("For n_clusters =", n_clusters, "The average silhouette_score is :", silhouette_avg)
        
#         # Compute the silhouette scores for each sample
#         sample_silhouette_values = silhouette_samples(x, cluster_labels)
#         y_lower = 10
#         for i in range(n_clusters):
#             ith_cluster_silhouette_values = sample_silhouette_values[cluster_labels == i]
#             ith_cluster_silhouette_values.sort()
#             size_cluster_i = ith_cluster_silhouette_values.shape[0]
#             y_upper = y_lower + size_cluster_i
#             color = cm.nipy_spectral(float(i) / n_clusters)
#             ax1.fill_betweenx(np.arange(y_lower, y_upper), 0, ith_cluster_silhouette_values,facecolor=color, edgecolor=color, alpha=0.7)

#             # Label the silhouette plots with their cluster numbers at the middle
#             ax1.text(-0.05, y_lower + 0.5 * size_cluster_i, str(i+1))
#             # Compute the new y_lower for next plot
#             y_lower = y_upper + 10  # 10 for the 0 samples

#         ax1.set_title("The silhouette plot for the various clusters.")
#         ax1.set_xlabel("The silhouette coefficient values")
#         ax1.set_ylabel("Cluster label")

#         # The vertical line for average silhouette score of all the values
#         ax1.axvline(x=silhouette_avg, color="red", linestyle="--")

#         ax1.set_yticks([])  # Clear the yaxis labels / ticks
#         ax1.set_xticks([-0.1, 0, 0.2, 0.4, 0.6, 0.8, 1])
    
#         #---------------------> Optimal K silhouette_
#         k_optimal = np.argmax(silhouette_) + 2
#         ax2.plot(range(2,n_clusters),silhouette_[:time],linestyle = '--',color = 'blue', linewidth =3, markersize= 8)
#         ax2.scatter(n_clusters,silhouette_avg)
#         time +=1
        
#         #Label and More
#         ax2.set_title('Silhouette Curve for optimal Number of clusters' , family = 'Arial', fontsize = 8)
#         ax2.set_xlabel(f'K={n_clusters}', fontsize = 14, family = 'Arial') 
#         ax2.set_ylabel('Silhouette_score', fontsize = 14, family = 'Arial')
#         ax2.axvline(x=k_optimal,label='Optimal number of cluster ({optimal})'.format(optimal=k_optimal),linestyle = '--', color ='red')
#         ax2.set_yticks(np.linspace(0.1,1,k))  
#         ax2.set_xticks(np.arange(2,k+1))
#         ax2.scatter(k_optimal ,silhouette_[k_optimal-2], color = 'red', s=100)
#         ax2.legend(fontsize = 'medium')
        
#         #---------------------> K - Elbow Method
#         ax3.set_title('Elbow method for Optimal K' , family = 'Arial', fontsize = 10)
#         ax3.plot(np.arange(2,n_clusters+1),Inertia[:time],linestyle = '--',color = 'blue', linewidth =3)
#         ax3.scatter(np.arange(2,n_clusters+1),Inertia[:time],color = 'red') #dots
#         ax3.scatter(n_clusters,clusterer.inertia_,color = 'red', s=100) #dots
#         ax3.set_xlabel('Number of Clusters')
#         ax3.set_ylabel('Inertia')
        
#       #---------------------> Bar Plot
#         '''
#         ax4.set_title('Cluster Distribution',family = 'Arial', fontsize = 8)
#         bar = sns.barplot(x=unique+1, y = counts ,palette='Paired')
#         bar.set_xticklabels(bar.get_xticklabels(),  rotation=90, horizontalalignment='right');
#         sns.despine(left=True, bottom=True ,ax=ax4)
#         ax4.get_yaxis().set_visible(False)
#         i=0


#         for p in bar.patches:
#             height = p.get_height()
#             bar.text(p.get_x()+p.get_width()/2., height + 0.1, counts[i],ha="center")
#             i += 1
#         '''

#     plt.show()
# Best_Kmean(x,10)


#### Cluster

In [64]:
# df3= df2
# df3['cluster']=cluster
# df3

In [65]:
# df3.isnull().sum()

In [66]:
# print(df3.product_weight_g.describe())
# print(df3.volume_cm3.describe())

In [67]:
# df_cluster=pd.DataFrame(df3.groupby('cluster').count().sort_values('product_id',ascending=False),columns=['product_id'])
# df_cluster.rename(columns={'product_id':'No_skus'},inplace=True)
# df_cluster['percentage']=(df_cluster['No_skus'].values/len(unique_products))*100
# conditions1 =[(df_cluster['percentage']>=30),(df_cluster['percentage']>=20)& (df_cluster['percentage']<30),(df_cluster['percentage']>=12.5)& (df_cluster['percentage']<20),(df_cluster['percentage']>=11.7)& (df_cluster['percentage']<12.5),(df_cluster['percentage']>=10)& (df_cluster['percentage']<11.7) , (df_cluster['percentage']<10),]
# zone= [1,2,3,4,5,6]
# df_cluster['zone']=np.select(conditions1,zone)
# df_cluster['pod_required']=round((df_cluster['No_skus']/len(shelves)))
# df_cluster['pod_required_zone_inventory_capacity']=round(df_cluster['pod_required']*1.167)
# df_cluster['No_rows_required']=df_cluster['pod_required_zone_inventory_capacity']/(c*10)
# print(df_cluster.pod_required.sum())
# print(df_cluster.pod_required_zone_inventory_capacity.sum())
# print(df_cluster.No_rows_required.sum())
# df_cluster


In [68]:
# import matplotlib.pyplot as plt
# import seaborn as sns
# sns.countplot(x=df3['cluster'], palette="plasma")
# fig = plt.gcf()
# fig.set_size_inches(10,10)
# plt.title('No skus by cluster')

In [69]:
# conditions =[(df3['cluster']==1),(df3['cluster']==3), (df3['cluster']==4), (df3['cluster']==5),(df3['cluster']==0) ,(df3['cluster']==2),]
# zones= [1,2,3,4,5,6]
# df3['zone']=np.select(conditions,zones)
# df3

In [70]:
# df3.zone.value_counts()

#### Neural network

In [71]:
# #Shuffle
# df4=df3
# np.random.seed(42)
# df3=df3.reindex(np.random.permutation(df3.index))
# df3.reset_index(inplace=True,drop=True)
# df3

In [72]:
# from sklearn import preprocessing

# #normalization
# min_max_scaler = preprocessing.MinMaxScaler()
# Dataset_normalize1 = min_max_scaler.fit_transform(df3.drop(['zone'],axis=1))
# np.shape(Dataset_normalize1)

In [73]:
# df7=pd.DataFrame(Dataset_normalize1)
# df7['target']=df3['zone']
# df7.dropna(axis=0,inplace=True)
# df7.reset_index(drop=True, inplace=True)
# df7

In [74]:
# df7['target'].isnull().sum()

In [75]:
# X=df7.drop('target',axis=1).values

In [76]:
# from sklearn.model_selection import train_test_split
# X_main,X_holdout,y_main,y_holdout=train_test_split(X,df7['target'],test_size=0.1,shuffle=True)


In [77]:
# from sklearn.preprocessing import OneHotEncoder
# ohe=OneHotEncoder()
# y= ohe.fit_transform(df7[['target']])
# y=y.todense()
# ohe.categories_

In [78]:
# X

In [79]:
# y

In [80]:
# df8=pd.DataFrame(y)
# df8

In [81]:
# index_y_holdout=y_holdout.index  
# index_y_main=y_main.index

In [82]:
# y_main_index_oh=df8.iloc[index_y_main]
# y_holdout_index_oh=df8.iloc[index_y_holdout]

In [83]:
# lenght1 = [X_main, y_main,X_holdout,y_holdout]

# for i in lenght1:
#     print(i.__class__, i.shape)

In [84]:
# # Create neuron networks
# from tensorflow.keras import models
# from tensorflow.keras import layers
# from tensorflow.keras import optimizers
# from tensorflow.keras.callbacks import Callback, ModelCheckpoint
# from tensorflow.keras.optimizers import Adam, SGD,RMSprop
# from sklearn.model_selection import KFold
# from keras.layers import Dropout
# #cross validate

# kf=KFold(4)
# oos_y=[]
# oos_pred=[]
# fold=0

# for train,test in kf.split(X_main):
#     fold+=1
#     print("Fold #{}".format(fold))

#     X_train=X[train]
#     y_train=Y[train]
#     X_test=X[test]
#     y_test=Y[test]

#     # Model
#     model = models.Sequential()

#     model.add(layers.Dense(512, activation='relu', input_shape=(7,)))
#     model.add(Dropout(0.2))
#     model.add(layers.Dense(218, activation='sigmoid'))
#     model.add(Dropout(0.2))
#     model.add(layers.Dense(6, activation='sigmoid'))

#     EPOCHS=30
#     INIT_LR=1e-1

#     # opt = Adam(learning_rate=INIT_LR, decay=INIT_LR / EPOCHS) 
#     # opt = SGD()
#     opt = RMSprop()
#     model.compile(optimizer=opt,
#                 loss='categorical_crossentropy',
#                 metrics=['acc'])
  
#     checkpoint = ModelCheckpoint(
#         'model1.h5', 
#         verbose=0, 
#         save_best_only=True, 
#         save_weights_only=False,
#         mode='auto'
#     )

#     history = model.fit(X_train,y_train,
#                         epochs=EPOCHS,
#                         batch_size=156,
#                         validation_data=( X_test,y_test),
#                         validation_split=0.1,
#                         callbacks=[checkpoint]

#                     )
   
    

In [85]:
# model.summary()

In [86]:
# lenght2 = [X_train, X_test,y_train,y_test]

# for i in lenght2:
#     print(i.__class__, i.shape)

In [87]:
# model.save('model1.h5')

In [88]:
# # plot the training loss and accuracy
# plt.style.use("ggplot")
# plt.figure(figsize=[14,12])
# N = EPOCHS
# plt.plot(np.arange(0, N), history.history["loss"], label="train_loss")
# plt.plot(np.arange(0, N), history.history["val_loss"], label="val_loss")
# plt.plot(np.arange(0, N), history.history["acc"], label="train_acc")
# plt.plot(np.arange(0, N), history.history["val_acc"], label="val_acc")
# plt.title("Training Loss and Accuracy ")
# plt.xlabel("Epoch #")
# plt.ylabel("Loss/Accuracy")
# plt.legend(loc="upper right")


In [89]:
# plt.figure(figsize=(8,5))

# x_values =[x+1 for x in range(10)]
# y_values_acc = history.history['acc']
# y_values_val = history.history['val_acc']
# plt.plot(x_values,y_values_acc,linewidth=3.0)
# plt.plot(x_values,y_values_val,linewidth=3.0)
# plt.xticks(x_values,[1,2,3,4,5,6,7,8,9,10])
# plt.ylabel('Accuracy')

# plt.xlabel('Epoch')
# plt.legend(['accuracy','val_accuracy']) 
# plt.show()

In [90]:
# plt.figure(figsize=(8,5))

# x_values =[x+1 for x in range(10)]
# y_values_acc = history.history['loss']
# y_values_val = history.history['val_loss']
# plt.plot(x_values,y_values_acc,linewidth=3.0)
# plt.plot(x_values,y_values_val,linewidth=3.0)
# plt.xticks(x_values,[1,2,3,4,5,6,7,8,9,10])
# plt.ylabel('Loss')

# plt.xlabel('Epoch')
# plt.legend(['accuracy','val_accuracy']) 
# plt.show()

In [91]:
# predictions = (model.predict(X_test))
# predictions

In [92]:
# y_test=ohe.inverse_transform(y_test)
# predictions=ohe.inverse_transform(predictions)

In [93]:
# oos_y.append(y_test)
# oos_pred.append(predictions)

In [94]:
# y_compare=np.argmax(y_test,axis=1)
# score1=metrics.accuracy_score(predictions,y_test)
# print('Fold score (accuracy): {}'.format(score1))

In [95]:
# holdout_pred= model.predict(X_holdout)
# holdout_pred=ohe.inverse_transform(holdout_pred)
# holdout_pred

In [96]:
# y_holdout=ohe.inverse_transform(y_holdout)

In [97]:
# y_holdout

In [98]:
# lenght2 = [holdout_pred,y_holdout]

# for i in lenght2:
#     print(i.__class__, i.shape)

In [99]:
# score2=metrics.accuracy_score(holdout_pred,y_holdout)
# print("Holdout Score (accuracy): {}".format(score2))

In [100]:
# from sklearn.metrics import f1_score
# f1_score(np.array(y_test),predictions,average='weighted')

In [101]:
# X_holdout=min_max_scaler.inverse_transform(X_holdout)
# X_holdout

In [102]:
# cols=['product_id','product_category_name']

# for col in cols:
#     X_holdout[col]=lbl.inverse_transform(X_holdout[col])
# X_holdout.head()

### Functions

In [103]:
import numpy as np
a = np.array([[[0,'b77f596e85780e540958a58d35836e96','1f08ab38da3a77a8e0bd17e63df35827'],['f56e93f8bec270456dd5ec3272bd42f3',0,'a042f8bfc21bceff9db6313d2f98aefc'],[0,'a042f8bfc21bceff9db6313d2f98aefc',0],[0,'b77f596e85780e540958a58d35836e96',0],['3487b8d662448326a09da14416640170',0,0]],[[0,0,0],[0,0,'6f04cbb6917432bdae4cdc802436f090'],[0,0,0],[0,'80298f0be0af5a4873f12e2521515281',0],[0,'3487b8d662448326a09da14416640170',0,]]],dtype=object)
a

array([[[0, 'b77f596e85780e540958a58d35836e96',
         '1f08ab38da3a77a8e0bd17e63df35827'],
        ['f56e93f8bec270456dd5ec3272bd42f3', 0,
         'a042f8bfc21bceff9db6313d2f98aefc'],
        [0, 'a042f8bfc21bceff9db6313d2f98aefc', 0],
        [0, 'b77f596e85780e540958a58d35836e96', 0],
        ['3487b8d662448326a09da14416640170', 0, 0]],

       [[0, 0, 0],
        [0, 0, '6f04cbb6917432bdae4cdc802436f090'],
        [0, 0, 0],
        [0, '80298f0be0af5a4873f12e2521515281', 0],
        [0, '3487b8d662448326a09da14416640170', 0]]], dtype=object)

#### Replenishment

In [104]:
#Check Association
def association (rules1:dict,dict_product_:dict,product_id_,category_,pods_layout_):
    relation=False
    position_i=[]
    position_j=[]
    
    if category_ in rules1.keys():
        if product_id_ in dict_product_.keys():
            for i in range(0,pods_layout_.shape[0]):
                for j in range(0,pods_layout_.shape[1]):
                    for k in range(0,len(pods_layout_[i][j])):
                        if pods_layout_[i][j][k] in dict_product_.keys():                     
                            if dict_product_[pods_layout_[i][j][k]][0] in rules1[category_]:   
                                position_j.append(j)
                                position_i.append(i)                                                                       
                                relation = True
                                break                         

                # position_j.append(j)
                            else:
                                position_i=list(np.arange(0,len(pods_layout_)+1))
                                print(position_i)  
                                                                                    
                        # else:
                            print('category of product stored not in rules')
                            position_i=list(np.arange(0,len(pods_layout_)+1))
                                
                    # else:
                        print('product not stored in general dictionary')
                        position_i=list(np.arange(0,len(pods_layout_)+1))
                                               
        else:
            print('product not in general dictionary')
            position_i=list(np.arange(0,len(pods_layout_)+1))
           
    else:
        print('category not in rules')
        position_i=list(np.arange(0,len(pods_layout_)+1))
    return relation,position_i#,position_j


In [105]:
association(rules1,dict_product_,'3c1fe640b9b303b8f12b612e350b9446','beleza_saude',a)

category not in rules


(False, [0, 1, 2])

In [106]:
filter=df2['product_id']=='6f04cbb6917432bdae4cdc802436f090'
df_filter=df2[filter]
df_filter

product_id  total_cost product_category_name  \
22421  6f04cbb6917432bdae4cdc802436f090      159.99            automotivo   

       product_weight_g  volume_cm3  average_daily_quantity       std  \
22421             100.0      2400.0                0.033333  1.154701   

       std_sigma  safety_stock  total_inventory  
22421          2         0.025              1.0

In [107]:
#Check product  Max inventory
def inventory(pods_layout_,product_id_):
    count=0
    for i in range(0,pods_layout_.shape[0]):
        for j in range(0,pods_layout_.shape[1]):
            for k in range(0,len(pods_layout_[i][j])):
                if pods_layout_[i][j][k]==product_id_:
                    count+=1
                else:
                    count=count

    return count                

In [108]:
inventory(a,'3487b8d662448326a09da14416640170')

2

In [109]:
#Check Product Weight
def p_weight (orders_:dict,product_id_):
    if product_id_ in orders_.keys():        
        return orders_[product_id_][2]
    else:
        pass
        

In [110]:
#Check Pod Max Weight
def pod_weight (dict_product_:dict,pods_layout_,first_position_i):
    pod_weight=0
    for i in range(0,pods_layout_.shape[0]):
        for j in range(0,pods_layout_.shape[1]):
            for k in range(0,len(pods_layout_[i][j])):
                if pods_layout_[first_position_i][j][k] in dict_product_.keys():
                    pod_weight+=dict_product_[pods_layout_[first_position_i][j][k]][2]                    
                else:
                    pass
        return pod_weight       

In [111]:
pod_weight(dict_product_,a,1)

775.0

In [112]:
# Check Product Volume
def volume (orders_:dict,product_id_):
    if product_id_ in orders_.keys():
        return orders_[product_id_][3]
    else:
        pass

In [113]:
# Check shelve Volume
def s_volume(dict_product_:dict,pods_layout_,first_position_i):
    volume=[]
   
    for i in range(1):
        for j in range(0,pods_layout_.shape[1]):
            for k in range(0,len(pods_layout_[i][j])):
                if pods_layout_[first_position_i][j][k] in dict_product_.keys():                               
                    volume.append((dict_product_[pods_layout_[first_position_i][j][k]][3]))                      
                else:
                    volume.append(0)
                                                  
    return np.sum(np.array(volume).reshape(-1,3),axis=1)#.reshape(-1,10)
               

In [114]:
s_volume(dict_product_,a,1)

array([    0.,  2400.,     0.,  1404., 48000.])

In [115]:
# Check Max Volume Shelve  
def volume_max(dict_product_:dict,orders_:dict,product_id_,first_position_i):
    volume_sh=s_volume(dict_product_,a,first_position_i) 
    condition4=[]
    position_j=[]
   
    for i in range(0,len(volume_sh)):
        condition4.append(volume_sh[i]+volume(orders_,product_id_))
    print(condition4)

    # for en , step in enumerate(range(0, len(condition4))):
    #     value = en+1    
    #     if (value % 5) == 0:      
    #         for j in range(value-5, value):
    for m in range(0,len(condition4)):
        if condition4[m]<total_shelve_volume:
            position_j.append(m)              
        # position_i.append(int((value/5)-1))
            
    return position_j
    

In [116]:
# Assign function to space in shelve
def put_in (pods_layout_,product_id_,position_j,first_position_i):
   
    put=False
    first_position_j=position_j[0]   
    iterator_j=iter(position_j)
    ka=[]
    while True:  
        try:
          
            for k in range(0,3):
               
                if pods_layout_[first_position_i][first_position_j][k]==0:
                    pods_layout_[first_position_i][first_position_j][k]=product_id_
                    print('first_position_j',first_position_j)
                    first_position_j=position_j[0]
                    ka.append(k)
                    print('position k',ka)                  
                    put=True
                    raise StopIteration
                    
                else:
                    for _ in range(0,1):
                        first_position_j=next(iterator_j)                     
                        print('search j',first_position_j)
                        k=0
                        break                                          
                            
        except StopIteration:
            break 
    return put
         

In [117]:
put_in(a,'16c4e87b98a9370a9cbc3a4658a3f45b',[0,1,2,3,4],0)

first_position_j 0
position k [0]


True

In [118]:
a

array([[['16c4e87b98a9370a9cbc3a4658a3f45b',
         'b77f596e85780e540958a58d35836e96',
         '1f08ab38da3a77a8e0bd17e63df35827'],
        ['f56e93f8bec270456dd5ec3272bd42f3', 0,
         'a042f8bfc21bceff9db6313d2f98aefc'],
        [0, 'a042f8bfc21bceff9db6313d2f98aefc', 0],
        [0, 'b77f596e85780e540958a58d35836e96', 0],
        ['3487b8d662448326a09da14416640170', 0, 0]],

       [[0, 0, 0],
        [0, 0, '6f04cbb6917432bdae4cdc802436f090'],
        [0, 0, 0],
        [0, '80298f0be0af5a4873f12e2521515281', 0],
        [0, '3487b8d662448326a09da14416640170', 0]]], dtype=object)

In [119]:
#Allocation function
def allocation (product_id_,pods_layout_,orders_:dict,dict_product_:dict,rules1_:dict):
    quantity_=orders_[product_id_][1]
    stored=[]
    not_stored=[]
    
    
      
    while quantity_>0:
        if product_id_ in dict_product_.keys():
            condition1=inventory(pods_layout_,product_id_) # CHECK THE WHOLE WAREHOUSE INVENTORY OF PRODUCT           
            if condition1< dict_product_[product_id_][1]: #CHECK WAREHOUSE INVENTORY IS LESS THAN TOTAL INVENTORY TO STORE
                condition2= association(rules1_,dict_product_,product_id_,orders_[product_id_][0],pods_layout_)       #RETURN IF THERE IF THERE IS RELATION, POSITION I        
                if condition2[0]==True:  #(True, [0, 0], [1, 2])
                    position_i=condition2[1]                   
                    first_position_i=int(position_i[0])                 
                    iterator_i=iter(position_i)
                    while True:
                        
                        try:                                                     
                            condition3= pod_weight(dict_product_,pods_layout_,first_position_i)+p_weight(orders_,product_id_) #TOTAL WEIGHT IN STAND + PRODUCT WEIGHT
                            print(condition3)
                            if condition3<total_pod_weight:
                                condition4=volume_max(dict_product_,orders_,product_id_,first_position_i) #RETURN POSITION J WITH VOLUME AVAILABLE
                                print(condition4)
                                position_j=condition4   
                                if position_j:
                                    locate=put_in(pods_layout_,product_id_,position_j,first_position_i)#SEARCH IN POSITION J IF POSITION K AVAILABLE AND ASSIGN
                                    if locate == True:                     
                                        quantity_-=1 
                                        # update_quantity=orders_[product_id_][1]-1
                                        # orders_[product_id_][1]=update_quantity
                                        stored.append(product_id_)
                                        print('stored',first_position_i)                           
                                        first_position_i=position_i[0]
                                        raise StopIteration

                                    else:
                                        for _ in range(0,1):
                                            first_position_i=next(iterator_i)
                                            print('ni1',first_position_i)
                                            break 
                                    
                                else:
                                    for _ in range(0,1):
                                        first_position_i=next(iterator_i)
                                        print('ni2',first_position_i)
                                        break 
                                    
                            else:
                                for _ in range(0,1):
                                    first_position_i=next(iterator_i)
                                    print('ni3',first_position_i)
                                    break               
                                            
                        except StopIteration:
                            break                                                                                                                 
                    
                else:
                    print('not relation')
                    position_i=condition2[1]                   
                    first_position_i=int(position_i[0])                 
                    iterator_i=iter(position_i)
                    while True:
                        
                        try:                                                     
                            condition3= pod_weight(dict_product_,pods_layout_,first_position_i)+p_weight(orders_,product_id_) #TOTAL WEIGHT IN STAND + PRODUCT WEIGHT
                            print(condition3)
                            if condition3<total_pod_weight:
                                condition4=volume_max(dict_product_,orders_,product_id_,first_position_i) #RETURN POSITION J WITH VOLUME AVAILABLE
                                print(condition4)
                                position_j=condition4   
                                if position_j:
                                    locate=put_in(pods_layout_,product_id_,position_j,first_position_i)#SEARCH IN POSITION J IF POSITION K AVAILABLE AND ASSIGN
                                    print(locate)
                                    if locate== True:
                                        stored.append(product_id_)
                                        print('stored',first_position_i)
                                        first_position_i=position_i[0]                     
                                        quantity_-=1 
                                        # update_quantity=orders_[product_id_][1]-1
                                        # orders_[product_id_][1]=update_quantity                                      
                                        raise StopIteration

                                    else:
                                        for _ in range(0,1):
                                            first_position_i=next(iterator_i)
                                            print('search i 1',first_position_i)
                                            break                                    
                                    
                                else:
                                    for _ in range(0,1):
                                        first_position_i=next(iterator_i)
                                        print('search i 2',first_position_i)
                                        break 
                                    
                            else:
                                for _ in range(0,1):
                                    first_position_i=next(iterator_i)
                                    print('search i 3',first_position_i)
                                    break               
                                           
                        except StopIteration:
                            break 
                       
            else:
                not_stored.append(product_id_)
                print('exceed limit inventory')
                break
                
                
        else:
            print('not in general dictionary of products')
            condition2= association(rules1_,dict_product_,product_id_,orders_[product_id_][0],pods_layout_)       #RETURN IF THERE IF THERE IS RELATION, POSITION I        
            if condition2[0]==True:  #(True, [0, 0], [1, 2])
                position_i=condition2[1]                   
                first_position_i=int(position_i[0])                 
                iterator_i=iter(position_i)
                while True:
                    
                    try:                                                     
                        condition3= pod_weight(dict_product_,pods_layout_,first_position_i)+p_weight(orders_,product_id_) #TOTAL WEIGHT IN STAND + PRODUCT WEIGHT
                        print(condition3)
                        if condition3<total_pod_weight:
                            condition4=volume_max(dict_product_,orders_,product_id_,first_position_i) #RETURN POSITION J WITH VOLUME AVAILABLE
                            print(condition4)
                            position_j=condition4   
                            if position_j:
                                locate=put_in(pods_layout_,product_id_,position_j,first_position_i)#SEARCH IN POSITION J IF POSITION K AVAILABLE AND ASSIGN
                                if locate == True:
                                    stored.append(product_id_)
                                    print('stored',first_position_i)                       
                                    quantity_-=1 
                                    # update_quantity=orders_[product_id_][1]-1                               
                                    # orders_[product_id_][1]=update_quantity                                                             
                                    first_position_i=position_i[0]
                                    raise StopIteration

                                else:
                                    for _ in range(0,1):
                                        first_position_i=next(iterator_i)
                                        print(' search i 1',first_position_i)
                                        break 
                                                                   
                            else:
                                for _ in range(0,1):
                                    first_position_i=next(iterator_i)
                                    print('search i 2',first_position_i)
                                    break 
                                
                        else:
                            for _ in range(0,1):
                                first_position_i=next(iterator_i)
                                print('search i 3',first_position_i)
                                break                                                
                                        
                    except StopIteration:
                        break                                
            
    return stored,not_stored
    

In [120]:
def replenish(pods_layout_,orders_:dict,dict_product_:dict,rules1_:dict):
    for i in orders_.keys():
        allocation(i,pods_layout_,orders_,dict_product_,rules1_)

In [121]:
#check available pods
pods_capacity=pod
def check_pods(pods_capacity):
        available_pods=np.sum(pods_layout==0)
        occupied_pods=np.sum(pods_layout !=0)
        current_pods_capacity=pods_capacity-occupied_pods
        print('Number of available pods =' ,available_pods)
        print('Number of occupied pods =' , occupied_pods)
        print('Current empty pods capacity =' , current_pods_capacity)   
        
check_pods(pods_layout)

#check empty shelves in the pods
shelves_capacity=pod*shelves
def check_shelves(shelves_layout):
        available_shelves=np.sum(shelves_layout==0)
        occupied_shelves=np.sum(shelves_layout!=0)
        current_shelves_capacity=shelves_capacity-occupied_shelves
        print('Number of available shelves =' ,available_shelves)
        print('Number of occupied shelves =' , occupied_shelves)
        print('Current empty shelves capacity =' , current_shelves_capacity)   
       
check_shelves(shelves_layout)       

Number of available pods = 115500
Number of occupied pods = 0
Current empty pods capacity = [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
Number of available shelves = 20
Number of occupied shelves = 0
Current empty shelves capacity = 38500


In [122]:
# #count inventory On hand
# def inventory(pods_layout_):
    

In [123]:
#Replenishment orders
import random
df_test=df2
df_test_replenish=df_test.sample(100)
df_test_replenish=df_test_replenish.drop(['total_cost','std','std_sigma','safety_stock','total_inventory','average_daily_quantity'],axis=1)
df_test_replenish.rename(columns={'Quantity_products_sold':'quantity_products_replenish'},inplace=True)
quantity_replenish=[]
for i in range(100):
    a=random.randint(1,4)
    quantity_replenish.append(a)
df_test_replenish['quantity_products_replenish']=quantity_replenish
df_test_replenish

product_id product_category_name  \
22684  9e8fcf395c0076ab46ac780f3d84ab93      moveis_decoracao   
8749   e30a07181e238b29af319577b9bb22fe          beleza_saude   
26417  32cb082100ed973a2e3a6950214f8629      malas_acessorios   
5069   aca27d7a91bfb10489d3e1aae184d137            perfumaria   
31607  1b46816aa838ce9ae97feda7b2f51f26      artigos_de_natal   
...                                 ...                   ...   
24584  9f3d5786e5d1ed02ec2d0a91849f64a5            brinquedos   
17177  305307f44f730d8ddd6db6e2efedee64       cama_mesa_banho   
32566  af5da61d100eab89aeb416514f688161    relogios_presentes   
31714  6b59816f789d2ecd9884ca8bbb81dd93     moveis_escritorio   
30223  3630657a252ca88c694edfa53f2ad9f2    ferramentas_jardim   

       product_weight_g  volume_cm3  quantity_products_replenish  
22684            1150.0     26000.0                            4  
8749             1100.0      4000.0                            4  
26417           19200.0    169400.0                            3  
5069              500.0      4500.0                            2  
31607             200.0      1260.0                            1  
...                 ...         ...                          ...  
24584             150.0       720.0                            4  
17177             700.0      3000.0                            2  
32566             300.0      3520.0                            3  
31714           14900.0     94192.0                            3  
30223             300.0       936.0                            2  

[100 rows x 5 columns]

In [124]:
product_id_=df_test_replenish['product_id'].tolist()
quantity_=df_test_replenish['quantity_products_replenish'].tolist()
category_=df_test_replenish['product_category_name'].tolist()
weight_=df_test_replenish['product_weight_g'].tolist()
volume_=df_test_replenish['volume_cm3'].tolist()

In [125]:
orders={}
for i,j,k,l,m in zip (product_id_,category_,quantity_,weight_,volume_):
    orders[i]=[j,k,l,m]
orders

{'9e8fcf395c0076ab46ac780f3d84ab93': ['moveis_decoracao', 4, 1150.0, 26000.0],
 'e30a07181e238b29af319577b9bb22fe': ['beleza_saude', 4, 1100.0, 4000.0],
 '32cb082100ed973a2e3a6950214f8629': ['malas_acessorios',
  3,
  19200.0,
  169400.0],
 'aca27d7a91bfb10489d3e1aae184d137': ['perfumaria', 2, 500.0, 4500.0],
 '1b46816aa838ce9ae97feda7b2f51f26': ['artigos_de_natal', 1, 200.0, 1260.0],
 'd66eeeb49d2801f33401c8c6828aee40': ['automotivo', 2, 700.0, 10000.0],
 'e59c256dc4c4c950e3c71ac153a18c9d': ['industria_comercio_e_negocios',
  4,
  1250.0,
  13455.0],
 'e336c656869480e20d04ca9389b12167': ['fashion_roupa_masculina',
  1,
  750.0,
  2125.0],
 '5b55f963a5c26f723ea1b5d7872557d3': ['papelaria', 3, 300.0, 10000.0],
 'fdfb90feb49d2b41b8283a8ec6e95590': ['instrumentos_musicais',
  4,
  11600.0,
  90000.0],
 '6b120063aeece762b2ef81da00c75ab9': ['brinquedos', 2, 600.0, 24000.0],
 '6a31191d5ac5852b0478f6e245ac5b02': ['utilidades_domesticas',
  4,
  1250.0,
  17052.0],
 '37a6534264082d880dbd603dae

In [126]:
replenish(pods_layout,orders,dict_product_,rules1)

category not in rules
not relation
1150.0


AttributeError: 'int' object has no attribute 'shape'

In [127]:
allocation('5ff6f5d729e40306d114d501700a838b',a,orders,dict_product_,rules1)

KeyError: '5ff6f5d729e40306d114d501700a838b'

In [ ]:
a

array([[['8d437dc54645e02e40d13fb2de911c1b',
         'd425f8ccf937bdc4c55eb96ef872d812',
         '1f08ab38da3a77a8e0bd17e63df35827'],
        ['f56e93f8bec270456dd5ec3272bd42f3', 0,
         'a042f8bfc21bceff9db6313d2f98aefc'],
        [0, 'a042f8bfc21bceff9db6313d2f98aefc', 0],
        [0, 0, 0],
        ['3487b8d662448326a09da14416640170', 0, 0]],

       [[0, 0, 0],
        [0, 0, '6f04cbb6917432bdae4cdc802436f090'],
        [0, 0, 0],
        [0, '80298f0be0af5a4873f12e2521515281', 0],
        [0, '3487b8d662448326a09da14416640170', 0]]], dtype=object)

In [ ]:
association(rules1,dict_product_,'6e423c2d28bfb207e1fd1d6e1df84721',orders['6e423c2d28bfb207e1fd1d6e1df84721'][0],a)

category not in rules


(False, [0, 1, 2])

In [ ]:
orders['6e423c2d28bfb207e1fd1d6e1df84721'][0]

'perfumaria'

In [ ]:
p_weight(orders,'6e423c2d28bfb207e1fd1d6e1df84721')

350.0

In [ ]:
volume(orders,'6e423c2d28bfb207e1fd1d6e1df84721')

2800.0

In [ ]:
volume_max(dict_product_,orders,'6e423c2d28bfb207e1fd1d6e1df84721',0)

[10990.0, 20200.0, 7000.0, 3600.0, 51600.0]


[0, 1, 2, 3, 4]

#### Picking

In [ ]:
#picking function

def picking (orders_picking_:dict,pods_layout_,product_id_:str):
    quantity_=orders_picking_[product_id_][1]
    product_picked=[]
    product_backorder=[]
    items_picked=0
    items_backorder=0
    result=False
    position_i_=[]
    
       
    while quantity_>0:
        try:
                    
            for i in range(0,pods_layout_.shape[0]):
                for j in range(0,pods_layout_.shape[1]):
                    for k in range (0,3):
                        if pods_layout_[i][j][k]== product_id_:
                            product_picked.append(product_id_)
                            pods_layout_[i][j][k]=0
                            position_i_.append(i)
                            result=True
                            if result==True:                                 
                                quantity_-=1                          
                                items_picked+=1
                                raise StopIteration

                            
                        
          

            product_backorder.append(product_id_)
            items_backorder+=1
            break
                                
                                
        
        except StopIteration:
            break
            
                    


    print('product_picked', product_picked)
    print('product_backorder',product_backorder)
    print('items_picked',items_picked,'items_backorder',items_backorder)

In [ ]:
#Picking orders
df_test_order=df_test.sample(5000)
df_test_order=df_test_order.drop(['total_cost','std','std_sigma','safety_stock','total_inventory','average_daily_quantity'],axis=1)
df_test_order.rename(columns={'Quantity_products_sold':'Quantity_products_picking'},inplace=True)
quantity=[]
for i in range(5000):
    a=random.randint(1,3)
    quantity.append(a)
df_test_order['Quantity_products_picking']=quantity
df_test_order

product_id        product_category_name  \
28143  fad8f41c2919d9bea348ae5792f8fc20  fashion_bolsas_e_acessorios   
26717  d34e5bf81263409f116d93ea7c9eda15                   brinquedos   
14577  56d3607592dec4aae037173a6cfd02f0                     pet_shop   
30513  542ad0ab955876d25ddf09684a3b3c5e              cama_mesa_banho   
18817  0ba8d6ed826271d06a9ebd6e3c3e8b3e                 beleza_saude   
...                                 ...                          ...   
29141  35c4a5bb0f191b77c8900661f047250b                esporte_lazer   
1057   810cb3c5af006624fa32d362077af85f                esporte_lazer   
24181  61d980017b9f55ac2451dbf0bdb849f2            moveis_escritorio   
4594   dd66beca916c169c2a77e40ae2858623              cama_mesa_banho   
10373  3609dcfca328f686e30517807ce959a9                 beleza_saude   

       product_weight_g  volume_cm3  Quantity_products_picking  
28143             200.0      1584.0                          3  
26717             225.0      5472.0                          1  
14577             300.0      4500.0                          2  
30513             500.0      8256.0                          3  
18817             400.0      1500.0                          1  
...                 ...         ...                        ...  
29141            1013.0      8970.0                          3  
1057             1252.0      4800.0                          3  
24181              50.0    141750.0                          1  
4594             3300.0     21000.0                          1  
10373            1150.0      4096.0                          1  

[5000 rows x 5 columns]

In [ ]:
product_id1_=df_test_order['product_id'].tolist()
quantity1_=df_test_order['Quantity_products_picking'].tolist()
category1_=df_test_order['product_category_name'].tolist()
weight1_=df_test_order['product_weight_g'].tolist()
volume1_=df_test_order['volume_cm3'].tolist()

In [ ]:
orders_picking={}
for i,j,k,l,m in zip (product_id1_,category1_,quantity1_,weight1_,volume1_):
    orders_picking[i]=[j,k,l,m]
orders_picking

{'fad8f41c2919d9bea348ae5792f8fc20': ['fashion_bolsas_e_acessorios',
  3,
  200.0,
  1584.0],
 'd34e5bf81263409f116d93ea7c9eda15': ['brinquedos', 1, 225.0, 5472.0],
 '56d3607592dec4aae037173a6cfd02f0': ['pet_shop', 2, 300.0, 4500.0],
 '542ad0ab955876d25ddf09684a3b3c5e': ['cama_mesa_banho', 3, 500.0, 8256.0],
 '0ba8d6ed826271d06a9ebd6e3c3e8b3e': ['beleza_saude', 1, 400.0, 1500.0],
 'd498e8a880bdf3d26e2b9b3e92c4f424': ['utilidades_domesticas',
  3,
  2350.0,
  3520.0],
 '6171e0ffb665e527d521c2435e065644': ['cool_stuff', 1, 400.0, 4560.0],
 'b224eb3c154415f1a25f604619f48b77': ['bebes', 1, 17200.0, 105300.0],
 '98ec655119c24de03b804696821f3955': ['beleza_saude', 2, 200.0, 12000.0],
 'd5e448e00fb7c59b31e0f3e43c2de0d7': ['cool_stuff', 2, 850.0, 35000.0],
 '89bab87bf3067b3e6614d53338c4d788': ['brinquedos', 2, 500.0, 4000.0],
 '9ab67e72832283a835980e86910ecf73': ['utilidades_domesticas',
  1,
  1150.0,
  27869.0],
 '626f55dacc29e4f934bdb3e4f3be83b4': ['construcao_ferramentas_ferramentas',
  3,

In [ ]:
picking(orders_picking,a,'b77f596e85780e540958a58d35836e96')

product_picked []
product_backorder ['b77f596e85780e540958a58d35836e96']
items_picked 0 items_backorder 1


In [ ]:
a

array([[[0, 0, '1f08ab38da3a77a8e0bd17e63df35827'],
        ['f56e93f8bec270456dd5ec3272bd42f3', 0,
         'a042f8bfc21bceff9db6313d2f98aefc'],
        [0, 'a042f8bfc21bceff9db6313d2f98aefc', 0],
        [0, 0, 0],
        ['3487b8d662448326a09da14416640170', 0, 0]],

       [[0, 0, 0],
        [0, 0, '6f04cbb6917432bdae4cdc802436f090'],
        [0, 0, 0],
        [0, '80298f0be0af5a4873f12e2521515281', 0],
        [0, '3487b8d662448326a09da14416640170', 0]]], dtype=object)